name:                trial-chain-api
version:             0.1.0.0
github:              "githubuser/trial-chain-api"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trial-chain-api#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- base16
- binary
- bytestring
- containers
- cryptonite
- deepseq
- memory
- mtl
- protolude
- servant
- servant-server
- servant-client
- http-client
- stm
- text
- wai
- warp

default-extensions:
# ----------
- StrictData
- BangPatterns
# ----------
- NoImplicitPrelude
# ----------
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoMonomorphismRestriction
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeSynonymInstances
- ViewPatterns

library:
  source-dirs: src

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    dependencies:
    - trial-chain-api

  load-test-exe:
    main:                Main.hs
    source-dirs:         load-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - trial-chain-api

tests:
  trial-chain-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - containers
    - hspec
    - hspec-core
    - hspec-wai
    - http-client
    - http-types
    - servant
    - servant-client
    - servant-server
    - stringsearch
    - text
    - trial-chain-api
    - unordered-containers
    - wai
    - wai-extra
    - warp
